### ISSUE TITLE
[p]heroclass issues

### ISSUE THREAD

**Issue by fixator10** [aikaterna/gobcog#89]
1. triggers cooldown when you in adventure (`The class hall is back in town.`)
2. Attempt to change class to nonexistent via `heroclass <non-existing-class> info` withdraws money without doing anything:
	1. try to use `[p]heroclass IDONTEXIST`
	2. bot says `Idontexist may be a class somewhere, but not on my watch.`, which makes sense
	3. try to use `[p]heroclass IDONTEXIST info`
	4. you can pay for class changing, but does nothing
3. heroclass withdraws money for any operation, including fail:
	1. Try to change class with lvl<10
	2. Bot shows menu `This will cost %amount%%currency%. Do you want to continue, %name%`
	3. Click ✅ emoji: money taken, but class not changed, bot says `%name%, you need to be at least level 10 to choose a class.`

**Comment by Drapersniper** [comment]
Fixed by #88 in https://github.com/aikaterna/gobcog/commit/e9984e85e1dde710b653ae9d1d5e4cc7f0224ffe

**Comment by aikaterna** [comment]
Fixator if you would like to comment on whether the recent merge resolved your issue(s) I would appreciate it before closing this.

**Comment by fixator10** [comment]
The 3rd issue with money withdrawal on fail is still an issue
![img](https://moeka.is-a-good-waifu.com/8XEk5Y6.png)

**Comment by aikaterna** [comment]
Should be resolved with a6b9052 if you can confirm.

**Comment by fixator10** [comment]
Well, seems like everything is fine now
![img](https://moeka.is-a-good-waifu.com/3L4s7T3.png)
